const ArtifactActionTypes = {
  FETCH_LIST_ARTIFACT_START: 'FETCH_LIST_ARTIFACT_START',
  FETCH_LIST_ARTIFACT_SUCCESS: 'FETCH_LIST_ARTIFACT_SUCCESS',
  FETCH_LIST_ARTIFACT_FAILURE: 'FETCH_LIST_ARTIFACT_FAILURE',
  SEARCH_ARTIFACT: "SEARCH_ARTIFACT",
};

export default ArtifactActionTypes;