export const WeaponActionTypes = {
  UPDATE_LISTWEAPON: 'UPDATE_LISTWEAPON',
  SEARCH_WEAPON: "SEARCH_WEAPON",
  CLEAR_SEARCH_WEAPON: "CLEAR_SEARCH_WEAPON",
  FILTER_TYPE_WEAPON: "FILTER_TYPE_WEAPON",
};
