export const WeaponActionTypes = {
  FETCH_LIST_WEAPON_START: 'FETCH_LIST_WEAPON_START',
  FETCH_LIST_WEAPON_SUCCESS: 'FETCH_LIST_WEAPON_SUCCESS',
  FETCH_LIST_WEAPON_FAILURE: 'FETCH_LIST_WEAPON_FAILURE',
  SEARCH_WEAPON: "SEARCH_WEAPON",
  CLEAR_SEARCH_WEAPON: "CLEAR_SEARCH_WEAPON",
  FILTER_TYPE_WEAPON: "FILTER_TYPE_WEAPON",
};
