const Weapon_Data = [
  {
    id: "WP0001",
    name: "Summit Shaper",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
  },
  {
    id: "WP0002",
    name: "Skyward Blade",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT Rate increased by 4/5/6/7/8%. Gains Skypiercing Might upon using an Elemental Burst: Increases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by 20/25/30/35/40% for 12s.",
  },
  {
    id: "WP0003",
    name: "Primordial Jade Cutter",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "HP increased by 20/25/30/35/40%. Additionally, provides an ATK bonus based on 1.2/1.5/1.8/2.1/2.4% of the weilder's Max HP.",
  },
  {
    id: "WP0004",
    name: "Mistsplitter Reforged",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "CRIT DMG",
    skill:
      "Gain a 12/15/18/21/24% Elemental DMG Bonus for every element and receive the might of Mistsplitter's Emblem. At stack levels 1/2/3, Mistsplitter's Emblem provides a 8/16/28% // 10/17/35% // 12/18/42% // 14/19/49% // 16/20/56% Elemental DMG Bonus for the character's Elemental Type. The character will obtain 1 stack of Mistsplitter's Emblem in each of the following scenarios: Normal Attack deals Elemental DMG (stack lasts 5s), casting Elemental Burst (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
  },
  {
    id: "WP0005",
    name: "Freedom-Sworn",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG by 10%. When characters with Freedom-Sworn trigger Elemental Reactions, they gain a Sigil of Rebellion (once every 0.5s). This triggers even if they aren't on the field. When you reach 2 Sigils, all will be consumed and grant all nearby party members +20% ATK and +16% Normal, Charged, and Plunging Attack DMG for 12s. Once triggered, you gain no Sigils for 20s. Buffs of the same type won't stack.",
  },
  {
    id: "WP0006",
    name: "Aquila Favonia",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "ATK is increased by 20%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of resistance aloft, regenerating HP equal to 100% of ATK and dealing 200% of ATK as DMG to surrounding enemies. This effect can only occur once every 15s.",
  },
  {
    id: "WP0007",
    name: "The Flute",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Normal or Charged Attacks grant Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100/125/150/175/200% ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.",
  },
  {
    id: "WP0008",
    name: "The Black Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "Increases DMG dealt by Normal and Charged Attacks by 20/25/30/35/40%. Additionally, regenerates 60/70/80/90/100% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.",
  },
  {
    id: "WP0009",
    name: "The Alley Flash",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG dealt by the character equipping this weapon by 12/15/18/21/24%. Taking DMG disables this effect for 5s.",
  },
  {
    id: "WP0010",
    name: "Sword of Descension",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.",
  },
  {
    id: "WP0011",
    name: "Sacrificial Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
  },
  {
    id: "WP0012",
    name: "Royal Longsword",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Upon damaging an enemy, increases CRIT Rate by 8/10/12/14/16%. Max 5 stacks. A CRIT hit removes all stacks.",
  },
  {
    id: "WP0013",
    name: "Prototype Rancour",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "On hit, Normal or Charged Attacks increase Base ATK and DEF by 4/4.5/5/5.5/6% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
  },
  {
    id: "WP0014",
    name: "Lion's Roar",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Increases DMG against enemies affected by Pyro or Electro by 20/24/28/32/36%.",
  },
  {
    id: "WP0015",
    name: "Iron Sting",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Dealing Elemental DMG increases all DMG by 6/7.5/9/10.5/12% for 6s. Max 2 stacks. Can only occur once every 1s.",
  },
  {
    id: "WP0016",
    name: "Festering Desire",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "Increases Elemental Skill DMG by 16/20/24/28/32% and Elemental Skill CRIT Rate by 6/7.5/9/10.5/12%.",
  },
  {
    id: "WP0017",
    name: "Favonius Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
  },
  {
    id: "WP0018",
    name: "Cinnabar Spindle",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "DEF",
    skill:
      "Elemental Skill DMG is increased by 40/50/60/70/80% of DEF. The effect will be triggered no more than once every 1.5s and will be cleared 0.1s after the Elemental Skill deals DMG.",
  },
  {
    id: "WP0019",
    name: "Blackcliff Longsword",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
  },
  {
    id: "WP0020",
    name: "Amenoma Kageuchi",
    imgSrc: "",
    type: "Sword",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "After casting an Elemental Skill, gain 1 Succession Seed. This effect can be triggered once every 5s. The Succession Seed lasts for 30s. Up to 3 Succession Seeds may exist simultaneously. After using an Elemental Burst, all Succession Seeds are consumed and after 2s, the character regenerates 6 Energy for each seed consumed.",
  },
  {
    id: "WP0021",
    name: "Traveler's Handy Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "DEF",
    skill:
      "Each Elemental Orb or Particle collected restores 1/1.25/1.5/1.75/2% HP.",
  },
  {
    id: "WP0022",
    name: "Skyrider Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "Energy Recharge",
    skill:
      "Using an Elemental Burst grants a 12/15/18/21/24% increase in ATK and Movement SPD for 12s.",
  },
  {
    id: "WP0023",
    name: "Harbinger of Dawn",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "CRIT DMG",
    skill: "When HP is above 90%, increases CRIT Rate by 14/18/22/24/28%.",
  },
  {
    id: "WP0024",
    name: "Fillet Blade",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "ATK",
    skill:
      "On hit, has 50% chance to deal 240/280/320/360/400% ATK DMG to a single enemy. Can only occur once every 15/14/13/12/11s.",
  },
  {
    id: "WP0025",
    name: "Dark Iron Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
  },
  {
    id: "WP0026",
    name: "Cool Steel",
    imgSrc: "",
    type: "Sword",
    rarity: 3,
    bonus_effect: "ATK",
    skill:
      "Increases DMG against enemies affected by Hydro or Cryo by 12/15/18/21/24%.",
  },
  {
    id: "WP0027",
    name: "Silver Sword",
    imgSrc: "",
    type: "Sword",
    rarity: 2,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0028",
    name: "Dull Blade",
    imgSrc: "",
    type: "Sword",
    rarity: 1,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0029",
    name: "Vortex Vanquisher",
    imgSrc: "",
    type: "Polearm",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
  },
  {
    id: "WP0030",
    name: "Staff of Homa",
    imgSrc: "",
    type: "Polearm",
    rarity: 5,
    bonus_effect: "CRIT DMG",
    skill:
      "HP increased by 20/25/30/35/40%. Additionally, provides an ATK Bonus based on 0.8/1/1.2/1.4/1.6% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK bonus is increased by an additional 1/1.2/1.4/1.6/1.8% of Max HP.",
  },
  {
    id: "WP0031",
    name: "Skyward Spine",
    imgSrc: "",
    type: "Polearm",
    rarity: 5,
    bonus_effect: "Energy Recharge",
    skill:
      "Increases CRIT Rate by 8/10/12/14/16% and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on enemies have a 50% chance to trigger a vacuum blade that deals 40/55/70/85/100% of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.",
  },
  {
    id: "WP0032",
    name: "Primordial Jade Winged-Spear",
    imgSrc: "",
    type: "Polearm",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "On hit, increases ATK by 3.2/3.9/4.6/5.3/6% for 6s. Max 7 stacks. This effect can only occur once every 0.3s. While in possession of the maximum possible stacks, DMG dealt is increased by 12/15/18/21/24%.",
  },
  {
    id: "WP0033",
    name: "Engulfing Lightning",
    imgSrc: "",
    type: "Polearm",
    rarity: 5,
    bonus_effect: "Energy Recharge",
    skill:
      "ATK increased by 28/34/40/46/52% of Energy Recharge over the base 100%. You can gain a maximum bonus of 80/90/100/110/120% ATK. Gain 30/35/40/45/50% Energy Recharge for 12s after using an Elemental Burst.",
  },
  {
    id: "WP0034",
    name: "The Catch",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "Increases Elemental Burst DMG by 16/20/24/28/32% and Elemental Burst CRIT Rate by 6/7.5/9/10.5/12%",
  },
  {
    id: "WP0035",
    name: "Royal Spear",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Upon damaging an opponent, increases CRIT Rate by 8/10/12/14/16%. Max 5 stacks. A CRIT hit removes all stacks.",
  },
  {
    id: "WP0036",
    name: "Prototype Grudge",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8/10/12/14/16% for 12s. Max 2 stacks.",
  },
  {
    id: "WP0037",
    name: "Lithic Spear",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "For every characters who hails from Liyue, the characters who equips this weapon gains 7/8/9/10/11% ATK increase and a 3/4/5/6/7% CRIT Rate increase. This effect stacks up to 4 times.",
  },
  {
    id: "WP0038",
    name: "Kitain Cross Spear",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "ncreases Elemental Skill DMG by 6%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
  },
  {
    id: "WP0039",
    name: "Favonius Lance",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
  },
  {
    id: "WP0040",
    name: "Dragon's Bane",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG against enemies affected by Hydro or Pyro by 20/24/28/32/36%.",
  },
  {
    id: "WP0041",
    name: "Dragonspine Spear",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "Hitting an opponent with Normal and Charged Attacks has a 60/70/80/90/100% chance of forming and dropping an Everfrost Icicle above them, dealing 80/95/110/125/140% AoE ATK DMG. Opponents affected by Cryo are dealt 200/240/280/320/360% ATK DMG. Can only occur once every 10s.",
  },
  {
    id: "WP0042",
    name: "Deathmatch",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "CRIT Rate",
    skill:
      "If there are at least 2 opponents nearby, ATK is increased by 16/20/24/28/32% and DEF is increased by 16/20/24/28/32%. If there are less than 2 enemies nearby, ATK is increased by 24/30/36/42/48%.",
  },
  {
    id: "WP0043",
    name: "Crescent Pike",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal an additional 20/25/30/35/40% ATK as DMG for 5s.",
  },
  {
    id: "WP0044",
    name: "Blackcliff Pole",
    imgSrc: "",
    type: "Polearm",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
  },
  {
    id: "WP0045",
    name: "White Tassel",
    imgSrc: "",
    type: "Polearm",
    rarity: 3,
    bonus_effect: "CRIT Rate",
    skill: "Increases Normal Attack DMG by 24/30/36/42/48%.",
  },
  {
    id: "WP0046",
    name: "Halberd",
    imgSrc: "",
    type: "Polearm",
    rarity: 3,
    bonus_effect: "ATK",
    skill:
      "Normal Attacks deal an additional 160/200/240/280/320% DMG. Can only occur once every 10s.",
  },
  {
    id: "WP0047",
    name: "Black Tassel",
    imgSrc: "",
    type: "Polearm",
    rarity: 3,
    bonus_effect: "HP",
    skill: "Increases DMG against slimes by 40/50/60/70/80%.",
  },
  {
    id: "WP0048",
    name: "Iron Point",
    imgSrc: "",
    type: "Polearm",
    rarity: 2,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0049",
    name: "Beginner's Protector",
    imgSrc: "",
    type: "Polearm",
    rarity: 1,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0050",
    name: "Wolf's Gravestone",
    imgSrc: "",
    type: "Claymore",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases ATK by 20/25/30/35/40%. On hit, attacks against enemies with less than 30% HP increase all party members' Base ATK by 40/50/60/70/80% for 12s. Can only occur once every 30s.",
  },
  {
    id: "WP0051",
    name: "The Unforged",
    imgSrc: "",
    type: "Claymore",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
  },
  {
    id: "WP0052",
    name: "Song of Broken Pines",
    imgSrc: "",
    type: "Claymore",
    rarity: 5,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "Increases the wielder’s ATK. When Normal or Charged Attacks hit opponents, the character gains a Sigil of Whispers (once every 0.3s). When you reach 4 Sigils, all will be consumed and all nearby party members will get increased Normal ATK SPD and ATK for 12s. Once this triggers, you gain no Sigils for 20s. Buffs of the same type won’t stack.",
  },
  {
    id: "WP0053",
    name: "Skyward Pride",
    imgSrc: "",
    type: "Claymore",
    rarity: 5,
    bonus_effect: "Energy Recharge",
    skill:
      "Increases all DMG by 8/10/12/14/16%. After using an Elemental Burst, Normal or Charged Attack, on hit, creates a vacuum blade that does 80/100/120/140/160% Physical DMG to enemies along its path. Lasts for 20s or 8 vacuum blades.",
  },
  {
    id: "WP0054",
    name: "Whiteblind",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "HP",
    skill:
      "Taking DMG generates a shield which absorbs DMG up to 20/23/26/29/32% of Max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by the shield, the character gains 12/15/18/21/24% increased DMG.",
  },
  {
    id: "WP0055",
    name: "The Bell",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "HP",
    skill:
      "Taking DMG generates a shield which absorbs DMG up to 20/23/26/29/32% of Max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by the shield, the character gains 12/15/18/21/24% increased DMG.",
  },
  {
    id: "WP0056",
    name: "Snow-Tombed Starsilver",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "Hitting an opponent with Normal and Charged Attacks has a 60/70/80/90/100% chance of forming and dropping an Everfrost Icicle above them, dealing 80/95/110/125/140% AoE ATK DMG. Opponents affected by Cryo are dealt 200/240/280/320/360% ATK DMG. Can only occur once every 10s.",
  },
  {
    id: "WP0057",
    name: "Serpent Spine",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "CRIT Rate",
    skill:
      "Every 4s a character is on the field, they will deal 6/7/8/9/10% more DMG and take 3/2.7/2.4/2.1/1.8% more DMG. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
  },
  {
    id: "WP0058",
    name: "Sacrificial Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
  },
  {
    id: "WP0059",
    name: "Royal Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Upon damaging an enemy, increases CRIT Rate by 8/10/12/14/16%. Max 5 stacks. A CRIT hit removes all stacks.",
  },
  {
    id: "WP0060",
    name: "Rainslasher",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG against enemies affected by Hydro or Electro by 20/25/30/35/40%.",
  },
  {
    id: "WP0061",
    name: "Prototype Aminus",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "On hit, Normal or Charged Attacks have a 50% chance to deal an additional 240/300/360/420/480% ATK DMG to enemies within a small radius. Can only occur once every 15s.",
  },
  {
    id: "WP0062",
    name: "Luxurious Sea-Lord",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Increases Elemental Burst DMG by 12/15/18/21/24%. When Elemental Burst hits opponents, there is a 100% chance of summoning a titanic tuna that charges and deals 100/125/150/175/200% ATK as AoE DMG. This effect can occur once every 15s.",
  },
  {
    id: "WP0063",
    name: "Lithic Blade",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "For every characters who hails from Liyue, the characters who equips this weapon gains 7/8/9/10/11% ATK increase and a 3/4/5/6/7% CRIT Rate increase. This effect stacks up to 4 times.",
  },
  {
    id: "WP0064",
    name: "Katsuragikiri Nagamasa",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "Increases Elemental Skill DMG by 6/7.5/9/10.5/12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3/3.5/4/4.5/5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
  },
  {
    id: "WP0065",
    name: "Favonius Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
  },
  {
    id: "WP0066",
    name: "Blackcliff Slasher",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
  },
  {
    id: "WP0067",
    name: "Akuoumaru",
    imgSrc: "",
    type: "Claymore",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "For every point of the entire party's combined maximum Energy capacity, the Elemental Burst DMG of the character equipping this weapon is increased by 0.12/0.15/0.18/0.21/0.24%. A maximum of 40/50/60/70/80% increased Elemental Burst DMG can be achieved this way.",
  },
  {
    id: "WP0068",
    name: "White Iron Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "DEF",
    skill: "Defeating an opponent restores 8/10/12/14/16% HP.",
  },
  {
    id: "WP0069",
    name: "Skyrider Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "On hit, Normal or Charged Attacks increase ATK by 6/7/8/9/10% for 6s. Max 4 stacks. Can only occur once every 0.5s.",
  },
  {
    id: "WP0070",
    name: "Quartz",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Upon causing an Overloaded, Melt, Burning, Vaporize, or a Pyro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
  },
  {
    id: "WP0071",
    name: "Ferrous Shadow",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "HP",
    skill:
      "When HP falls below 70/75/80/85/90%, increases Charged Attack DMG by 30/35/40/45/50%, and Charged Attacks become much harder to interrupt.",
  },
  {
    id: "WP0072",
    name: "Debate Club",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "ATK",
    skill:
      "After using an Elemental Skill, Normal or Charged Attacks, on hit, deal an additional 60/75/90/105/120% ATK DMG in a small area. Effect lasts 15s. DMG can only occur once every 3s.",
  },
  {
    id: "WP0073",
    name: "Bloodtainted Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG against enemies affected by Pyro or Electro by 12/15/18/21/24%.",
  },
  {
    id: "WP0074",
    name: "Old Merc's Pal",
    imgSrc: "",
    type: "Claymore",
    rarity: 2,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0075",
    name: "Waster Greatsword",
    imgSrc: "",
    type: "Claymore",
    rarity: 1,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0076",
    name: "Skyward Atlas",
    imgSrc: "",
    type: "Catalyst",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases Elemental DMG Bonus by 12/15/18/21/24%. Normal Attack hits have a 50% chance to earn the favor of the clouds. which actively seek out nearby enemies to attack for 15s, dealing 160/200/240/280/320% ATK DMG. Can only occur once every 30s.",
  },
  {
    id: "WP0077",
    name: "Lost Prayer to the Sacred Winds",
    imgSrc: "",
    type: "Catalyst",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "Increases Movement SPD by 10%. When in battle, earn a 6/8/10/12/14% Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.",
  },
  {
    id: "WP0078",
    name: "Memory of Dust",
    imgSrc: "",
    type: "Catalyst",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increase Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
  },
  {
    id: "WP0079",
    name: "Everlasting Moonglow",
    imgSrc: "",
    type: "Catalyst",
    rarity: 5,
    bonus_effect: "HP",
    skill:
      "Healing Bonus increased by 10/12.5/15/17.5/20%, Normal Attack DMG is increased by 1/1.5/2/2.5/3% of the Max HP of the character equipping this weapon. For 12s after using an Elemental Burst, Normal Attacks that hit opponents will restore 0.6 Energy. Energy can be restored this way once every 0.1s.",
  },
  {
    id: "WP0080",
    name: "Wine and Song",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "For every character in the party who hails from Mondstadt, the character who equips this weapon gains 8/10/12/14/16% ATK increase and 3/3.5/4/4.5/5% Movement SPD increase.",
  },
  {
    id: "WP0081",
    name: "The Widsith",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "When a character takes the field, they will gain a random theme song for 10s. This can only occur once every 30s. Recitative: Increases Base ATK by 60/75/90/105/120% Aria: Increases all Elemental DMG by 48/60/72/84/96% Interlude: Elemental Mastery is increased by 240/300/360/420/480",
  },
  {
    id: "WP0082",
    name: "Solar Pearl",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "CRIT Rate",
    skill:
      "Normal Attack hits increase Elemental Skill and Elemental Burst DMG by 20/25/30/35/40% for 6s. Likewise, Elemental Skill or Elemental Burst hits increase Normal Attack DMG by 20/25/30/35/40% for 6s.",
  },
  {
    id: "WP0083",
    name: "Sacrificial Fragments",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
  },
  {
    id: "WP0084",
    name: "Royal Grimoire",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Upon damaging an enemy, increases CRIT Rate by 8/10/12/14/16%. Max 5 stacks. A CRIT hit removes all stacks.",
  },
  {
    id: "WP0085",
    name: "Prototype Amber",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "HP",
    skill:
      "Using an Elemental Burst regenerates 4/4.5/5/5.5/6 Energy every 2s for 6s. Additionally, all party members will regenerate 4/4.5/5/5.5/6% HP every 2s for this duration.",
  },
  {
    id: "WP0086",
    name: "Mappa Mare",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Triggering an Elemental reaction grants a 8/10/12/14/16% Elemental DMG Bonus for 10s. Max 2 stacks.",
  },
  {
    id: "WP0087",
    name: "Hakushin Ring",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "After the character equipped with this weapon triggers an Electro elemental reaction, nearby party members of an Elemental Type involved in the elemental reaction receive a 10% Elemental DMG Bonus for their element, lasting 6s. Elemental Bonuses gained in this way cannot be stacked.",
  },
  {
    id: "WP0088",
    name: "Frostbearer",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Hitting an opponent with Normal and Charged Attacks has a 60/70/80/90/100% chance of forming and dropping an Everfrost Icicle above them, dealing 80/95/110/125/140% AoE ATK DMG. Opponents affected by Cryo are dealt 200/240/280/320/360% ATK DMG. Can only occur once every 10s.",
  },
  {
    id: "WP0089",
    name: "Favonius Codex",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
  },
  {
    id: "WP0090",
    name: "Eye of Perception",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Normal and Charged Attacks have a 50% chance to fire a Bolt of Perception, dealing 240/270/300/330/360% ATK as DMG. This bolt can bounce between enemies a maximum of 4 times. This effect can occur once every 12/11/10/9/8s.",
  },
  {
    id: "WP0091",
    name: "Dodoco Tales",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Normal Attack hits on opponents increase Charged Attack DMG by 16/20/24/28/32% for 6s. Charged Attack hits on opponents increase ATK by 8/10/12/14/16% for 6s.",
  },
  {
    id: "WP0092",
    name: "Blackcliff Amulet",
    imgSrc: "",
    type: "Catalyst",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
  },
  {
    id: "WP0093",
    name: "Twin Nephrite",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "CRIT Rate",
    skill:
      "Defeating an enemy increases Movement SPD and ATK by 12/14/16/18/20% for 15s.",
  },
  {
    id: "WP0094",
    name: "Thrilling Tales of Dragon Slayers",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "HP",
    skill:
      "When switching characters, the new character taking the field has their ATK increased by 24/30/36/42/48% for 10s. This effect can only occur once every 20s.",
  },
  {
    id: "WP0095",
    name: "Otherworldly Story",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "Energy Recharge",
    skill:
      "Each Elemental Orb or Particle collected restores 1/1.25/1.5/1.75/2% HP.",
  },
  {
    id: "WP0096",
    name: "Magic Guide",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG against enemies affected by Hydro or Electro by 12/15/18/21/24%.",
  },
  {
    id: "WP0097",
    name: "Emerald Orb",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Upon causing a Vaporize, Electro-Charged, Frozen, or a Hydro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
  },
  {
    id: "WP0098",
    name: "Amber Catalyst",
    imgSrc: "",
    type: "Catalyst",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Normal Attack hits increase all Elemental DMG by 6/7.5/9/10.5/12% for 6s. Max 2 stacks.",
  },
  {
    id: "WP0099",
    name: "Pocket Grimoire",
    imgSrc: "",
    type: "Catalyst",
    rarity: 2,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0100",
    name: "Apprentice's Notes",
    imgSrc: "",
    type: "Catalyst",
    rarity: 1,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0101",
    name: "Thundering Pulse",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "CRIT DMG",
    skill:
      "Increases ATK by 20/25/30/35/40% and grants the might of the Thunder Emblem. At stack levels 1/2/3, the Thunder Emblem increases Normal Attack DMG by 12/24/40%. The character will obtain 1 stack of Thunder Emblem in each of the following scenarios: Normal Attack deals DMG (stack lasts 5s), casting Elemental Skill (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
  },
  {
    id: "WP0102",
    name: "Skyward Harp",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "Increases CRIT DMG by 20/25/30/35/40%. Hits have a 60/70/80/90/100% chance to inflict a small AoE attack, dealing 125% Physical ATK DMG. Can only occur once every 4/3.5/3/2.5/2s.",
  },
  {
    id: "WP0103",
    name: "Polar Star",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "Elemental Skill and Elemental Burst DMG increased by 12/15/18/21/24%. After a Normal Attack, Charged Attack, Elemental Skill or Elemental Burst hits an opponent, 1 stack of Ashen Nightstar will be gained for 12s. When 1/2/3/4 stacks of Ashen Nightstar are present, ATK is increased by 10/20/30/48%. The stack of Ashen Nightstar created by the Normal Attack, Charged Attack, Elemental Skill or Elemental Burst will be counted independently of the others.",
  },
  {
    id: "WP0104",
    name: "Elegy for the End",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "Energy Recharge",
    skill:
      "Increased Elemental Mastery by 60. Gain sigils when dealing damage with Elemental Skill or Burst. Elemental Mastery increased by 100 and ATK increased by 20% at 4 sigils.",
  },
  {
    id: "WP0105",
    name: "Amos' Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "ATK",
    skill:
      "Increases Normal Attack and Aimed Shot DMG by 12/15/18/21/24%. Increases DMG from arrows shot by a further 8/10/12/14/16% for every 0.1s that the arrow is in flight, up to 0.5s. Stacks up to 5 times on each arrow.",
  },
  {
    id: "WP0106",
    name: "Windblume Ode",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "After using an Elemental Skill, receive a boon from the ancient wish of the Windblume, increasing ATK by 16/20/24/28/32% for 6s.",
  },
  {
    id: "WP0107",
    name: "The Viridescent Hunt",
    imgSrc: "",
    type: "Bow",
    rarity: 5,
    bonus_effect: "CRIT Rate",
    skill:
      "Upon hit, Normal and Aimed Shot Attacks have a 50% chance to generate a Cyclone, which will continuously attract surrounding enemies, dealing 40/50/60/70/80% of ATK as DMG to these enemies every 0.5s for 4s. This effect can only occur once every 14/13/12/11/10s.",
  },
  {
    id: "WP0108",
    name: "The Stringless",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases Elemental Skill and Elemental Burst DMG by 24/30/36/42/48%.",
  },
  {
    id: "WP0109",
    name: "Sacrificial Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
  },
  {
    id: "WP0110",
    name: "Rust",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Increases Normal Attack DMG by 40/50/60/70/80% but decreases Aimed Shot DMG by 8/9/10/11/12%",
  },
  {
    id: "WP0111",
    name: "Royal Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Upon damaging an enemy, increases CRIT Rate by 8/10/12/14/16%. Max 5 stacks. A CRIT hit removes all stacks.",
  },
  {
    id: "WP0112",
    name: "Prototype Crescent",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Aimed Shot hits on weak points increase Movement SPD by 10% and ATK by 36/45/54/63/72% for 10s.",
  },
  {
    id: "WP0113",
    name: "Predator",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Dealing Cryo DMG to opponents increases this character's Normal and Charged Attack DMG by 10% for 6s. This effect can have a maximum of 2 stacks. Additionally, when Aloy equips Predator, ATK is increased by 66.",
  },
  {
    id: "WP0114",
    name: "Mitternachts Waltz",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "Normal Attack hits on opponents increase Elemental Skill DMG by 20/25/30/35/40% for 5s. Elemental Skill hits on opponents increase Normal Attack DMG by 20/25/30/35/40% for 5s.",
  },
  {
    id: "WP0115",
    name: "Hamayumi",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "ATK",
    skill:
      "Increases Normal Attack DMG by 16% and Charged Attack DMG by 12%. When the equipping character's Energy reaches 100%, this effect is increased by 100%.",
  },
  {
    id: "WP0116",
    name: "Favonius Warbow",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Energy Recharge",
    skill:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
  },
  {
    id: "WP0117",
    name: "Compound Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "Physical DMG Bonus",
    skill:
      "Normal Attack and Aimed Shot hits increase ATK by 4/5/6/7/8% and Normal Attack SPD by 1.2/1.5/1.8/2.1/2.4% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
  },
  {
    id: "WP0118",
    name: "Blackcliff Warbow",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "CRIT DMG",
    skill:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
  },
  {
    id: "WP0119",
    name: "Alley Hunter",
    imgSrc: "",
    type: "Bow",
    rarity: 4,
    bonus_effect: "CRIT Rate",
    skill:
      "Every 4s a character is on the field, their ATK increases by 4/5/6/7/8% and their CRIT DMG increases by 4/5/6/7/8%. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
  },
  {
    id: "WP0120",
    name: "Slingshot",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "CRIT Rate",
    skill:
      "If a Normal Attack or Aimed Shot hits a target within 0.3s of being fired, increases DMG by 36/42/48/54/60%; otherwise, it decreases DMG by 10%.",
  },
  {
    id: "WP0121",
    name: "Sharpshooter's Oath",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "CRIT DMG",
    skill: "Increases DMG against weak spots by 24/30/36/42/48%.",
  },
  {
    id: "WP0122",
    name: "Recurve Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "HP",
    skill: "Defeating an opponent restores 8/10/12/14/16% HP.",
  },
  {
    id: "WP0123",
    name: "Raven Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "Elemental Mastery",
    skill:
      "Increases DMG against enemies affected by Hydro or Pyro by 12/15/18/21/24%.",
  },
  {
    id: "WP0124",
    name: "Messenger",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "CRIT DMG",
    skill:
      "Aimed Shot hits on weak spots deal an additional 100/125/150/175/200% ATK DMG as CRIT DMG. Can only occur once every 10s.",
  },
  {
    id: "WP0125",
    name: "Ebony Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 3,
    bonus_effect: "ATK",
    skill: "Increases DMG against mechanoid Ruin enemies by 40/50/60/70/80%.",
  },
  {
    id: "WP0126",
    name: "Seasoned Hunter's Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 2,
    bonus_effect: "-",
    skill: "-",
  },
  {
    id: "WP0127",
    name: "Hunter's Bow",
    imgSrc: "",
    type: "Bow",
    rarity: 1,
    bonus_effect: "-",
    skill: "-",
  },
];

export default Weapon_Data;