const Character_Data = {
  anemo: {
    id: 1,
    title: "anemo",
    routeName: "anemo",
    visionImgSrc: '/assets/vision/anemo.png',
    characters: [
      {
        id: 'A0001',
        name: "Traveler",
        imgSrc: "/assets/character/traveler-anemo.png",
        linkUrl: "traveler_anemo",
      },
      {
        id: 'A0002',
        name: "Jean",
        imgSrc: "/assets/character/jean.png",
        linkUrl: "jean",
      },
      {
        id: 'A0003',
        name: "Venti",
        imgSrc: "/assets/character/venti.png",
        linkUrl: "venti",
      },
      {
        id: 'A0004',
        name: "Sucrose",
        imgSrc: "/assets/character/sucrose.png",
        linkUrl: "sucrose",
      },
      {
        id: 'A0005',
        name: "Xiao",
        imgSrc: "/assets/character/xiao.png",
        linkUrl: "xiao",
      },
      {
        id: 'A0006',
        name: "Kazuha",
        imgSrc: "/assets/character/kazuha.png",
        linkUrl: "kazuha",
      },
      {
        id: 'A0007',
        name: "Sayu",
        imgSrc: "/assets/character/sayu.png",
        linkUrl: "sayu",
      },
    ],
  },
  pyro: {
    id: 2,
    title: "pyro",
    routeName: "pyro",
    visionImgSrc: '/assets/vision/pyro.png',
    characters: [
      {
        id: 'P0001',
        name: "Amber",
        imgSrc: "/assets/character/amber.png",
        linkUrl: "amber",
      },
      {
        id: 'P0002',
        name: "Diluc",
        imgSrc: "/assets/character/diluc.png",
        linkUrl: "diluc",
      },
      {
        id: 'P0003',
        name: "Yoimiya",
        imgSrc: "/assets/character/yoimiya.png",
        linkUrl: "yoimiya",
      },
      {
        id: 'P0004',
        name: "Benneth",
        imgSrc: "/assets/character/benneth.png",
        linkUrl: "benneth",
      },
      {
        id: 'P0005',
        name: "Klee",
        imgSrc: "/assets/character/klee.png",
        linkUrl: "klee",
      },
      {
        id: 'P0006',
        name: "Hutao",
        imgSrc: "/assets/character/hutao.png",
        linkUrl: "hutao",
      },
      {
        id: 'P0007',
        name: "Xiangling",
        imgSrc: "/assets/character/xiangling.png",
        linkUrl: "xiangling",
      },
      {
        id: 'P0009',
        name: "Xinyan",
        imgSrc: "/assets/character/xinyan.png",
        linkUrl: "xinyan",
      },
      {
        id: 'P0010',
        name: "Yanfei",
        imgSrc: "/assets/character/yanfei.png",
        linkUrl: "yanfei",
      },
    ],
  },
  electro: {
    id: 3,
    title: "electro",
    routeName: "electro",
    visionImgSrc: '/assets/vision/electro.png',
    characters: [
      {
        id: 'E0001',
        name: "Lisa",
        imgSrc: "/assets/character/lisa.png",
        linkUrl: "lisa",
      },
      {
        id: 'E0002',
        name: "Razor",
        imgSrc: "/assets/character/razor.png",
        linkUrl: "razor",
      },
      {
        id: 'E0003',
        name: "Fischl",
        imgSrc: "/assets/character/fischl.png",
        linkUrl: "fischl",
      },
      {
        id: 'E0004',
        name: "Beidou",
        imgSrc: "/assets/character/beidou.png",
        linkUrl: "beidou",
      },
      {
        id: 'E0005',
        name: "Keqing",
        imgSrc: "/assets/character/keqing.png",
        linkUrl: "keqing",
      },
      {
        id: 'E0006',
        name: "Shogun",
        imgSrc: "/assets/character/raiden.png",
        linkUrl: "shogun",
      },
      {
        id: 'E0007',
        name: "Sara",
        imgSrc: "/assets/character/sara.png",
        linkUrl: "sara",
      },
      {
        id: 'E0008',
        name: "Traveler",
        imgSrc: "/assets/character/traveler-electro.png",
        linkUrl: "traveler_electro",
      },
    ],
  },
  cryo: {
    id: 4,
    title: "cryo",
    routeName: "cryo",
    visionImgSrc: '/assets/vision/cryo.png',
    characters: [
      {
        id: 'C0001',
        name: "Rosaria",
        imgSrc: "/assets/character/rosaria.png",
        linkUrl: "rosaria",
      },
      {
        id: 'C0002',
        name: "Kaeya",
        imgSrc: "/assets/character/kaeya.png",
        linkUrl: "kaeya",
      },
      {
        id: 'C0003',
        name: "Eula",
        imgSrc: "/assets/character/eula.png",
        linkUrl: "eula",
      },
      {
        id: 'C0004',
        name: "Diona",
        imgSrc: "/assets/character/diona.png",
        linkUrl: "diona",
      },
      {
        id: 'C0005',
        name: "Aloy",
        imgSrc: "/assets/character/aloy.png",
        linkUrl: "aloy",
      },
      {
        id: 'C0006',
        name: "Chongyun",
        imgSrc: "/assets/character/chongyun.png",
        linkUrl: "chongyun",
      },
      {
        id: 'C0007',
        name: "Ayaka",
        imgSrc: "/assets/character/ayaka.png",
        linkUrl: "ayaka",
      },
      {
        id: 'C0008',
        name: "Ganyu",
        imgSrc: "/assets/character/ganyu.png",
        linkUrl: "ganyu",
      },
      {
        id: 'C0009',
        name: "Qiqi",
        imgSrc: "/assets/character/qiqi.png",
        linkUrl: "qiqi",
      },
    ],
  },
  geo: {
    id: 5,
    title: "geo",
    routeName: "geo",
    visionImgSrc: '/assets/vision/geo.png',
    characters: [
      {
        id: 'G0001',
        name: "Noelle",
        imgSrc: "/assets/character/noelle.png",
        linkUrl: "noelle",
      },
      {
        id: 'G0002',
        name: "Albedo",
        imgSrc: "/assets/character/albedo.png",
        linkUrl: "albedo",
      },
      {
        id: 'G0003',
        name: "Ningguang",
        imgSrc: "/assets/character/ningguang.png",
        linkUrl: "ningguang",
      },
      {
        id: 'G0004',
        name: "Traveler",
        imgSrc: "/assets/character/traveler-geo.png",
        linkUrl: "traveler_geo",
      },
      {
        id: 'G0005',
        name: "Zhongli",
        imgSrc: "/assets/character/zhongli.png",
        linkUrl: "zhongli",
      },
    ],
  },
  hydro: {
    id: 6,
    title: "hydro",
    routeName: "hydro",
    visionImgSrc: '/assets/vision/hydro.png',
    characters: [
      {
        id: 'H0001',
        name: "Tartaglia",
        imgSrc: "/assets/character/tartaglia.png",
        linkUrl: "tartaglia",
      },
      {
        id: 'H0002',
        name: "Barbara",
        imgSrc: "/assets/character/barbara.png",
        linkUrl: "barbara",
      },
      {
        id: 'H0003',
        name: "Xingqiu",
        imgSrc: "/assets/character/xingqiu.png",
        linkUrl: "xingqiu",
      },
      {
        id: 'H0004',
        name: "Kokomi",
        imgSrc: "/assets/character/kokomi.png",
        linkUrl: "kokomi",
      },
      {
        id: 'H0005',
        name: "Mona",
        imgSrc: "/assets/character/mona.png",
        linkUrl: "mona",
      },
    ],
  },
};

export default Character_Data;
