const Character_Data = {
  anemo: {
    id: 1,
    title: "anemo",
    routeName: "anemo",
    visionImgSrc: '/assets/vision/anemo.png',
    characters: [
      {
        id: 1,
        name: "Traveler",
        imgSrc: "/assets/character/traveler-anemo.png",
        linkUrl: "traveler_anemo",
      },
      {
        id: 2,
        name: "Jean",
        imgSrc: "/assets/character/jean.png",
        linkUrl: "jean",
      },
      {
        id: 3,
        name: "Venti",
        imgSrc: "/assets/character/venti.png",
        linkUrl: "venti",
      },
      {
        id: 4,
        name: "Sucrose",
        imgSrc: "/assets/character/sucrose.png",
        linkUrl: "sucrose",
      },
      {
        id: 5,
        name: "Xiao",
        imgSrc: "/assets/character/xiao.png",
        linkUrl: "xiao",
      },
      {
        id: 6,
        name: "Kazuha",
        imgSrc: "/assets/character/kazuha.png",
        linkUrl: "kazuha",
      },
      {
        id: 7,
        name: "Sayu",
        imgSrc: "/assets/character/sayu.png",
        linkUrl: "sayu",
      },
    ],
  },
  pyro: {
    id: 2,
    title: "pyro",
    routeName: "pyro",
    visionImgSrc: '/assets/vision/pyro.png',
    characters: [
      {
        id: 8,
        name: "Amber",
        imgSrc: "/assets/character/amber.png",
        linkUrl: "amber",
      },
      {
        id: 9,
        name: "Diluc",
        imgSrc: "/assets/character/diluc.png",
        linkUrl: "diluc",
      },
      {
        id: 10,
        name: "Yoimiya",
        imgSrc: "/assets/character/yoimiya.png",
        linkUrl: "yoimiya",
      },
      {
        id: 11,
        name: "Benneth",
        imgSrc: "/assets/character/benneth.png",
        linkUrl: "benneth",
      },
      {
        id: 12,
        name: "Klee",
        imgSrc: "/assets/character/klee.png",
        linkUrl: "klee",
      },
      {
        id: 13,
        name: "Hutao",
        imgSrc: "/assets/character/hutao.png",
        linkUrl: "hutao",
      },
      {
        id: 14,
        name: "Xiangling",
        imgSrc: "/assets/character/xiangling.png",
        linkUrl: "xiangling",
      },
      {
        id: 15,
        name: "Xinyan",
        imgSrc: "/assets/character/xinyan.png",
        linkUrl: "xinyan",
      },
      {
        id: 16,
        name: "Yanfei",
        imgSrc: "/assets/character/yanfei.png",
        linkUrl: "yanfei",
      },
    ],
  },
  electro: {
    id: 3,
    title: "electro",
    routeName: "electro",
    visionImgSrc: '/assets/vision/electro.png',
    characters: [
      {
        id: 17,
        name: "Lisa",
        imgSrc: "/assets/character/lisa.png",
        linkUrl: "lisa",
      },
      {
        id: 18,
        name: "Razor",
        imgSrc: "/assets/character/razor.png",
        linkUrl: "razor",
      },
      {
        id: 19,
        name: "Fischl",
        imgSrc: "/assets/character/fischl.png",
        linkUrl: "fischl",
      },
      {
        id: 20,
        name: "Beidou",
        imgSrc: "/assets/character/beidou.png",
        linkUrl: "beidou",
      },
      {
        id: 21,
        name: "Keqing",
        imgSrc: "/assets/character/keqing.png",
        linkUrl: "keqing",
      },
      {
        id: 22,
        name: "Shogun",
        imgSrc: "/assets/character/raiden.png",
        linkUrl: "shogun",
      },
      {
        id: 23,
        name: "Sara",
        imgSrc: "/assets/character/sara.png",
        linkUrl: "sara",
      },
      {
        id: 24,
        name: "Traveler",
        imgSrc: "/assets/character/traveler-electro.png",
        linkUrl: "traveler_electro",
      },
    ],
  },
  cryo: {
    id: 4,
    title: "cryo",
    routeName: "cryo",
    visionImgSrc: '/assets/vision/cryo.png',
    characters: [
      {
        id: 25,
        name: "Rosaria",
        imgSrc: "/assets/character/rosaria.png",
        linkUrl: "rosaria",
      },
      {
        id: 26,
        name: "Kaeya",
        imgSrc: "/assets/character/kaeya.png",
        linkUrl: "kaeya",
      },
      {
        id: 27,
        name: "Eula",
        imgSrc: "/assets/character/eula.png",
        linkUrl: "eula",
      },
      {
        id: 28,
        name: "Diona",
        imgSrc: "/assets/character/diona.png",
        linkUrl: "diona",
      },
      {
        id: 29,
        name: "Aloy",
        imgSrc: "/assets/character/aloy.png",
        linkUrl: "aloy",
      },
      {
        id: 30,
        name: "Chongyun",
        imgSrc: "/assets/character/chongyun.png",
        linkUrl: "chongyun",
      },
      {
        id: 31,
        name: "Ayaka",
        imgSrc: "/assets/character/ayaka.png",
        linkUrl: "ayaka",
      },
      {
        id: 32,
        name: "Ganyu",
        imgSrc: "/assets/character/ganyu.png",
        linkUrl: "ganyu",
      },
      {
        id: 33,
        name: "Qiqi",
        imgSrc: "/assets/character/qiqi.png",
        linkUrl: "qiqi",
      },
    ],
  },
  geo: {
    id: 5,
    title: "geo",
    routeName: "geo",
    visionImgSrc: '/assets/vision/geo.png',
    characters: [
      {
        id: 34,
        name: "Noelle",
        imgSrc: "/assets/character/noelle.png",
        linkUrl: "noelle",
      },
      {
        id: 35,
        name: "Albedo",
        imgSrc: "/assets/character/albedo.png",
        linkUrl: "albedo",
      },
      {
        id: 36,
        name: "Ningguang",
        imgSrc: "/assets/character/ningguang.png",
        linkUrl: "ningguang",
      },
      {
        id: 37,
        name: "Traveler",
        imgSrc: "/assets/character/traveler-geo.png",
        linkUrl: "traveler_geo",
      },
      {
        id: 38,
        name: "Zhongli",
        imgSrc: "/assets/character/zhongli.png",
        linkUrl: "zhongli",
      },
    ],
  },
  hydro: {
    id: 6,
    title: "hydro",
    routeName: "hydro",
    visionImgSrc: '/assets/vision/hydro.png',
    characters: [
      {
        id: 39,
        name: "Tartaglia",
        imgSrc: "/assets/character/tartaglia.png",
        linkUrl: "tartaglia",
      },
      {
        id: 40,
        name: "Barbara",
        imgSrc: "/assets/character/barbara.png",
        linkUrl: "barbara",
      },
      {
        id: 41,
        name: "Xingqiu",
        imgSrc: "/assets/character/xingqiu.png",
        linkUrl: "xingqiu",
      },
      {
        id: 42,
        name: "Kokomi",
        imgSrc: "/assets/character/kokomi.png",
        linkUrl: "kokomi",
      },
      {
        id: 43,
        name: "Mona",
        imgSrc: "/assets/character/mona.png",
        linkUrl: "mona",
      },
    ],
  },
};

export default Character_Data;
