const CharacterActionTypes = {
  FETCH_LIST_CHARACTERS_START: 'FETCH_LIST_CHARACTERS_START',
  FETCH_LIST_CHARACTERS_SUCCESS: 'FETCH_LIST_CHARACTERS_SUCCESS',
  FETCH_LIST_CHARACTERS_FAILURE: 'FETCH_LIST_CHARACTERS_FAILURE',
  FETCH_CHARACTERS_DETAIL_START: 'FETCH_CHARACTERS_DETAIL_START',
  FETCH_CHARACTERS_DETAIL_SUCCESS: 'FETCH_CHARACTERS_DETAIL_SUCCESS',
  FETCH_CHARACTERS_DETAIL_FAILURE: 'FETCH_CHARACTERS_DETAIL_FAILURE',
  SEARCH_CHARACTER: "SEARCH_CHARACTER",
};
 
export default CharacterActionTypes;