export const CharacterActionTypes = {
  FETCH_LIST_CHARACTERS_START: 'FETCH_LIST_CHARACTERS_START',
  FETCH_LIST_CHARACTERS_SUCCESS: 'FETCH_LIST_CHARACTERS_SUCCESS',
  FETCH_LIST_CHARACTERS_FAILURE: 'FETCH_LIST_CHARACTERS_FAILURE',
  SEARCH_CHARACTER: "SEARCH_CHARACTER",
  CLEAR_SEARCH_CHARACTER: "CLEAR_SEARCH_CHARACTER",
};
 